### ISSUE TITLE
Do not using my GPU

### ISSUE THREAD

**Issue by Lee-JeongMin** [thtrieu/darkflow#1027]
I training my own dataset.
But, darkflow is not using my GPU.
How to use GPU?
MY command is 
`CUDA_VISIBLE_DEVICES=1 python3 flow --model ./cfg/my-yolo.cfg --labels ./labels.txt --dataset ./data/corn_img/ --annotation ./data/Result_corn_old/ --train --batch 16 --epoch 100 --save 10 --keep 5 --lr 1e-04 --gpu 0.9 --gpuName /gpu:2
`
I already tried to --gpu 1.0  but, darkflow only use CPU.

AND do you know how to use multi gpus?
i have 4 gpus(0,1,2,3) but I use only 2 gpus(2,3)

**Comment by weiwei106** [comment]
I meet the same issues.

**Comment by weiwei106** [comment]
> I training my own dataset.
> But, darkflow is not using my GPU.
> How to use GPU?
> MY command is
> `CUDA_VISIBLE_DEVICES=1 python3 flow --model ./cfg/my-yolo.cfg --labels ./labels.txt --dataset ./data/corn_img/ --annotation ./data/Result_corn_old-batch 32 --epoch 10000 --save 1000 --keep 50 --lr 1e-04 --gpu 0.9 `
> I already tried to --gpu 1.0 but, darkflow only use CPU.
> 
> AND do you know how to use multi gpus?
> i have 4 gpus(0,1,2,3) but I use only 2 gpus(2,3)
> 
> How can i fix it??

maybe you can use other tensorflow vrsion.

**Comment by Lee-JeongMin** [comment]
I fixed it!  I’m using tensorflow 1.6.0 
It is no matter.
I use docker, I add tensorflow enviroment on docker.
So i use GPU, but i think can’t using multi GPU.

**Comment by yo3hcv** [comment]
I had the same issue (Windows 7, GTX1070)
Basically tensorflow-gpu depends on many other packages, pip install is not sufficient.

I uninstalled everything, than let conda to manage all

conda install tensorflow-gpu

Now it works great, confirmed by GPU-Z
