### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by borasy** [thtrieu/darkflow#241]
I just updated to the latest commit with the new clihandler stuffs, and i got error when training. Before this commit my training worked fine.

I tried:
 -lowering and increasing gpu usage => doesn't work
 -decreasing batch size => doesn't work

python3.5 flow --train --model cfg/yolo-sak.cfg --load bin/yolo.weights --gpu 0.9 --trainer adam --dataset Fire/ --annotation AnnotationFire/ --batch 32 --epoch 60 --save 22040

`ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,304,304,64]
	 [[Node: gradients/4-leaky_grad/GreaterEqual = GreaterEqual[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](mul_1, BiasAdd_1)]]
	 [[Node: mul_31/_117 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_6011_mul_31", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]`

Please help

**Comment by abagshaw** [comment]
@borasy Are you 100% sure that nothing else has changed (i.e. you got an updated `yolo.weights` or changed some other parameter of training)?

**Comment by borasy** [comment]
@abagshaw
Updated `yolo.weights` ?? I thought during training, the loaded weight doesn't change. Only the .ckpt that gets updated. Isn't it right?
And by training parameters you mean the .cfg? But i didn't change anything there.. just the filters size of last layer and class size.

**Comment by abagshaw** [comment]
By updated `yolo.weights` I meant downloading a newer version from https://pjreddie.com/media/files/yolo.weights. Could you try downloading the `yolo.weights` file from that link and then re-try your train command?

**Comment by borasy** [comment]
Okay, I'm trying your suggestion. Will report asap.

**Comment by borasy** [comment]
@abagshaw 
I tried your suggestion. And it's really strange. At first I got my original error above. And second time, I can't even parse the weights anymore. 

`Parsing ./cfg/yolo.cfg
Parsing cfg/yolo-sak.cfg
Loading bin/yolo.weights ...
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/mnt/hdd3t/Data/hci1/rasy/darkflow/darkflow/cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/mnt/hdd3t/Data/hci1/rasy/darkflow/darkflow/net/build.py", line 57, in __init__
    darknet = Darknet(FLAGS)
  File "/mnt/hdd3t/Data/hci1/rasy/darkflow/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/mnt/hdd3t/Data/hci1/rasy/darkflow/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/mnt/hdd3t/Data/hci1/rasy/darkflow/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/mnt/hdd3t/Data/hci1/rasy/darkflow/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/mnt/hdd3t/Data/hci1/rasy/darkflow/darkflow/utils/loader.py", line 77, in load
    walker.offset, walker.size)
AssertionError: expect 202314760 bytes, found 203934260 `

**Comment by borasy** [comment]
I solved the above problem by just cloning the project anew. But my original error still persists.
P.S. `yolo.weights` : (203,934,260 bytes)

**Comment by thtrieu** [comment]
@borasy, yolo.cfg is updated but .weights was not. Please see #247

**Comment by borasy** [comment]
@abagshaw i solved that already. No longer .cfg miss match with .weights. 
The problem now is back to my original problem which is `ResourceExhaustedError`

**Comment by borasy** [comment]
Anyway, I did some experiments and found that the FLAG gpuName doesn't really work. It doesn't matter which GPU i assign, all GPUs are used equally according to --gpu usage amount. 
e.g. --gpu 1.0 all gpu are used 100%,
      --gpu 0.1 all gpu are used 1%

And even at --gpu 0.1 `ResourceExhaustedError` still persists.
 
I suspect it has something to do with the new commits about gpu handling.

@thtrieu

**Comment by thtrieu** [comment]
`--gpuName` is to indicate which gpu amongst many that you are having.
`--gpu` indicates which percentage of **that gpu** you chose.

So:
> It doesn't matter which GPU i assign, all GPUs are used equally according to --gpu usage amount.
> e.g. --gpu 1.0 all gpu are used 100%,
> --gpu 0.1 all gpu are used 1%

Sounds obvious to me.  Have you ever tried no gpu at all?

**Comment by borasy** [comment]
@thtrieu I mean isn't the gpuName flag supposed to let us choose one gpu among the many gpus that we have to run darkflow? Because when i put the flag --gpuName /gpu:3 --gpu 1.0. I see that all my gpus 0,1,2,3 are used at 100% instead of just gpu number 3 to use at 100%.

Anyway, I tried training without gpu flag and the training works fine. And with the fact that i can train on gpu on previous version means there must be something wrong with the new commits about gpu handling stuffs.

**Comment by thtrieu** [comment]
Thanks for the input. Can you try the new code to see if it work now?

**Comment by borasy** [comment]
I just tried the new code.. Same problem. all 4 gpus are used.
I tried printing the --gpuname flag and see that the flag arg is passed through.. before `Building net ...`
Anyway, still got ResourceExhaustedError

**Comment by borasy** [comment]
hi @thtrieu @abagshaw 
i did some more experiments and found this:
- my forked old version of darkflow [(945749c)](https://github.com/borasy/darkflow/commits/master) + new cfg (608x608) => also produces ResourceExhaustedError
- latest version of darkflow + old cfg (416x416) => works fine 

Do you guys have any clue of what should I do next to solve this?

**Comment by mursalal** [comment]
Hello. I have same problem with @borasy. @borasy read this https://github.com/AlexeyAB/darknet/issues/39. I changed cfg to 1088x1088. I have not this issue without any gpu flags, but training is long

|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   38C    P8    18W / 125W |     72MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GRID K520           Off  | 0000:00:04.0     Off |                  N/A |
| N/A   33C    P8    17W / 125W |     37MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GRID K520           Off  | 0000:00:05.0     Off |                  N/A |
| N/A   35C    P8    17W / 125W |     37MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GRID K520           Off  | 0000:00:06.0     Off |                  N/A |
| N/A   31C    P8    17W / 125W |     37MiB /  4036MiB |      0%      Default |

**Comment by zhanglamei** [comment]
i found that add the flag  CUDA_VISIBLE_DEVICES can choose which GPU you use.

**Comment by borasy** [comment]
@zhanglamei that's great, can you tell me how to do that? I'm  not familiar with CUDA_VISIBLE_DEVICES flag

**Comment by zhanglamei** [comment]
CUDA_VISIBLE_DEVICES=0 ./flow --model cfg/yolo-voc.cfg --load /your model --train --annotation /your annotation  --dataset /your dataset --gpu 0.8
just like this.

**Comment by borasy** [comment]
Thanks a lot, it works.

**Comment by uwmyuan** [comment]
@thtrieu @abagshaw @zhanglamei 

Hi! I run the following code and got the similar error. I got only one gpu with label=0 and used the flag as @zhanglamei suggested. However, it did not work for any non-zero value of gpu usage setting.

Thanks.

Code:
```
CUDA_VISIBLE_DEVICES=0 ./flow --model cfg/tiny-yolo-voc-traffic.cfg --load -1 --train --dataset "~/Downloads/StanfordDroneDataset/sdd/JPEGImages" --annotation "~/Downloads/StanfordDroneDataset/sdd/Annotations" --gpu 0.001
```
Prompt:
```
Parsing cfg/tiny-yolo-voc-traffic.cfg
Loading None ...
Finished in 8.106231689453125e-05s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 16)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 16)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 32)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | maxp 2x2p0_1                     | (?, 13, 13, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 55)
-------+--------+----------------------------------+---------------
GPU mode with 0.01 usage
cfg/tiny-yolo-voc-traffic.cfg loss hyper-parameters:
	H       = 13
	W       = 13
	box     = 5
	classes = 6
	scales  = [1.0, 5.0, 1.0, 1.0]
Building cfg/tiny-yolo-voc-traffic.cfg loss
Building cfg/tiny-yolo-voc-traffic.cfg train op
2017-11-17 09:02:57.920080: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 09:02:57.920098: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 09:02:57.920115: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 09:02:57.920120: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 09:02:57.920151: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 09:02:57.990351: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-17 09:02:57.990703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 960
major: 5 minor: 2 memoryClockRate (GHz) 1.253
pciBusID 0000:06:00.0
Total memory: 1.95GiB
Free memory: 1.56GiB
2017-11-17 09:02:57.990730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-11-17 09:02:57.990734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-11-17 09:02:57.990756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:06:00.0)
2017-11-17 09:03:08.194203: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 18.00MiB.  Current allocation summary follows.
2017-11-17 09:03:08.194245: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (256): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194252: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (512): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194257: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1024): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194262: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2048): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194266: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4096): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194269: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8192): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194273: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16384): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194277: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (32768): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194281: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (65536): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194285: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (131072): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194289: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (262144): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194293: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (524288): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194310: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194313: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194317: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4194304): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194323: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8388608): 	Total Chunks: 1, Chunks in use: 0 13.94MiB allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194327: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194331: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194335: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194339: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194342: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (268435456): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2017-11-17 09:03:08.194347: I tensorflow/core/common_runtime/bfc_allocator.cc:660] Bin for 18.00MiB was 16.00MiB, Chunk State: 
2017-11-17 09:03:08.194351: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d00000 of size 1280
2017-11-17 09:03:08.194354: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d00500 of size 256
2017-11-17 09:03:08.194356: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d00600 of size 1792
2017-11-17 09:03:08.194359: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d00d00 of size 256
2017-11-17 09:03:08.194362: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d00e00 of size 256
2017-11-17 09:03:08.194364: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d00f00 of size 256
2017-11-17 09:03:08.194367: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d01000 of size 256
2017-11-17 09:03:08.194369: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d01100 of size 18432
2017-11-17 09:03:08.194372: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d05900 of size 256
2017-11-17 09:03:08.194374: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d05a00 of size 256
2017-11-17 09:03:08.194389: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d05b00 of size 256
2017-11-17 09:03:08.194391: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d05c00 of size 256
2017-11-17 09:03:08.194394: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d05d00 of size 73728
2017-11-17 09:03:08.194396: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d17d00 of size 256
2017-11-17 09:03:08.194399: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d17e00 of size 256
2017-11-17 09:03:08.194401: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d17f00 of size 256
2017-11-17 09:03:08.194404: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d18000 of size 512
2017-11-17 09:03:08.194407: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d18200 of size 294912
2017-11-17 09:03:08.194409: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d60200 of size 512
2017-11-17 09:03:08.194412: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d60400 of size 512
2017-11-17 09:03:08.194414: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d60600 of size 512
2017-11-17 09:03:08.194417: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d60800 of size 1024
2017-11-17 09:03:08.194419: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703d60c00 of size 1179648
2017-11-17 09:03:08.194422: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703e80c00 of size 1024
2017-11-17 09:03:08.194425: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703e81000 of size 1024
2017-11-17 09:03:08.194427: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703e81400 of size 1024
2017-11-17 09:03:08.194430: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703e81800 of size 2048
2017-11-17 09:03:08.194432: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x703e82000 of size 4718592
2017-11-17 09:03:08.194435: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x704302000 of size 2048
2017-11-17 09:03:08.194437: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x704302800 of size 2048
2017-11-17 09:03:08.194440: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x704303000 of size 2048
2017-11-17 09:03:08.194443: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x704303800 of size 4096
2017-11-17 09:03:08.194445: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x704304800 of size 14621440
2017-11-17 09:03:08.194448: I tensorflow/core/common_runtime/bfc_allocator.cc:693]      Summary of in-use Chunks by size: 
2017-11-17 09:03:08.194451: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 12 Chunks of size 256 totalling 3.0KiB
2017-11-17 09:03:08.194454: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 512 totalling 2.0KiB
2017-11-17 09:03:08.194457: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 1024 totalling 4.0KiB
2017-11-17 09:03:08.194460: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1280 totalling 1.2KiB
2017-11-17 09:03:08.194463: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1792 totalling 1.8KiB
2017-11-17 09:03:08.194466: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 2048 totalling 8.0KiB
2017-11-17 09:03:08.194469: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 4096 totalling 4.0KiB
2017-11-17 09:03:08.194472: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 18432 totalling 18.0KiB
2017-11-17 09:03:08.194475: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 73728 totalling 72.0KiB
2017-11-17 09:03:08.194478: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 294912 totalling 288.0KiB
2017-11-17 09:03:08.194481: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1179648 totalling 1.12MiB
2017-11-17 09:03:08.194484: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 4718592 totalling 4.50MiB
2017-11-17 09:03:08.194487: I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 6.02MiB
2017-11-17 09:03:08.194491: I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                    20931543
InUse:                     6309888
MaxInUse:                  6309888
NumAllocs:                      32
MaxAllocSize:              4718592

2017-11-17 09:03:08.194498: W tensorflow/core/common_runtime/bfc_allocator.cc:277] *******************************_____________________________________________________________________
2017-11-17 09:03:08.194509: W tensorflow/core/framework/op_kernel.cc:1182] Resource exhausted: OOM when allocating tensor of shape [3,3,512,1024] and type float
2017-11-17 09:03:08.196980: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Resource exhausted: OOM when allocating tensor of shape [3,3,512,1024] and type float
	 [[Node: 18-convolutional/kernel/Initializer/Const = Const[_class=["loc:@18-convolutional/kernel"], dtype=DT_FLOAT, value=Tensor<type: float shape: [3,3,512,1024] values: [[[-0.0074622505 0.0096569993 0.012990603]]]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Traceback (most recent call last):
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/yunyuan/anaconda/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor of shape [3,3,512,1024] and type float
	 [[Node: 18-convolutional/kernel/Initializer/Const = Const[_class=["loc:@18-convolutional/kernel"], dtype=DT_FLOAT, value=Tensor<type: float shape: [3,3,512,1024] values: [[[-0.0074622505 0.0096569993 0.012990603]]]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/yunyuan/darkflow/darkflow/cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/yunyuan/darkflow/darkflow/net/build.py", line 76, in __init__
    self.setup_meta_ops()
  File "/home/yunyuan/darkflow/darkflow/net/build.py", line 146, in setup_meta_ops
    self.sess.run(tf.global_variables_initializer())
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor of shape [3,3,512,1024] and type float
	 [[Node: 18-convolutional/kernel/Initializer/Const = Const[_class=["loc:@18-convolutional/kernel"], dtype=DT_FLOAT, value=Tensor<type: float shape: [3,3,512,1024] values: [[[-0.0074622505 0.0096569993 0.012990603]]]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op '18-convolutional/kernel/Initializer/Const', defined at:
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/yunyuan/darkflow/darkflow/cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/yunyuan/darkflow/darkflow/net/build.py", line 75, in __init__
    self.build_forward()
  File "/home/yunyuan/darkflow/darkflow/net/build.py", line 115, in build_forward
    state = op_create(*args)
  File "/home/yunyuan/darkflow/darkflow/net/ops/__init__.py", line 27, in op_create
    return op_types[layer_type](*args)
  File "/home/yunyuan/darkflow/darkflow/net/ops/baseop.py", line 39, in __init__
    self.convert(feed)
  File "/home/yunyuan/darkflow/darkflow/net/ops/baseop.py", line 47, in convert
    self.wrap_variable(var)
  File "/home/yunyuan/darkflow/darkflow/net/ops/baseop.py", line 74, in wrap_variable
    initializer = self.lay.w[var])
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 725, in _get_single_variable
    validate_shape=validate_shape)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 199, in __init__
    expected_shape=expected_shape)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 277, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 701, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py", line 203, in __call__
    verify_shape=verify_shape)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 106, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yunyuan/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [3,3,512,1024] and type float
	 [[Node: 18-convolutional/kernel/Initializer/Const = Const[_class=["loc:@18-convolutional/kernel"], dtype=DT_FLOAT, value=Tensor<type: float shape: [3,3,512,1024] values: [[[-0.0074622505 0.0096569993 0.012990603]]]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

```

**Comment by zhanglamei** [comment]
I think it's the problem that out of memory. 
You can check that your GPU only use 1% in "GPU mode with 0.01 usage".

**Comment by uwmyuan** [comment]
@zhanglamei 
Thanks for your kind reponse.
I tried `--gpu 1.0 0.5 0.25 0.1 0.01`. And the prompt were same. As you see, my gpu has `Free memory: 1.56GiB`. How much gpu memory should I allocate to this task?

**Comment by averdones** [comment]
I got the same error as @uwmyuan. Training on cpu works. Training on gpu, with a single 6GB gpu does not.

 Any updates?

**Comment by borasy** [comment]
@uwmyuan it's not just about how much GPU you allocate but also the batch size. If you allow 100% GPU capacity, but use big batch size like 100 , you will get OOM.

**Comment by linydf** [comment]
@borasy @abagshaw @thtrieu @zhanglamei @uwmyuan 
hello anybody, I train yolo2 model, I use change gpu 0.01,and batchsize 1 but still met this error? my
gpu only have 2G freedom
ResourceExhaustedError (see above for traceback): OOM when allocating tensor of
shape [512] and type float
         [[Node: 28-convolutional/gamma/Initializer/Const = Const[_class=["loc:@
28-convolutional/gamma"], dtype=DT_FLOAT, value=Tensor<type: float shape: [512]
values: 0.00377030438 -0.0112543032 0.00429944...>, _device="/job:localhost/repl
ica:0/task:0/device:GPU:0"]()]]

**Comment by SrikanthVelpuri** [comment]
I have 4GB graphic card of Nvidia 840m Ram 8 GB Processor i7....Now I got
the same error...I read in the issues that nvidia 1080 can run when batch
size is changed to 12 when yolo weights are used...Yolo architecture needs
more graphic card memory...You can use tiny-yolo-voc weights for
training...It might run on your GPU..check out those in readme of darkflow.

**Comment by linydf** [comment]
@SrikanthVelpuri thanks you answer,I used the tiny-yolo-voc ,it works but come this error
![5656](https://user-images.githubusercontent.com/32791070/38608645-7f0cd28a-3dae-11e8-8e94-2b6b5a472495.jpg)

**Comment by AndreCostaWind** [comment]
I have two GPUs with 2GB (1050).
My solution was put "gpu: 0".
I turned off the GPUs and trained directly on the CPU.
Slower. But it still does.
