### ISSUE TITLE
Resource exhaustion when train on own dataset

### ISSUE THREAD

**Issue by benn94** [thtrieu/darkflow#318]
I tried to train on my own dataset by identifying only two classes 
so classes = 2
and filter = 35 which is 5*(2+5)

`flow --model cfg/yolo_kitti.cfg --load bin/yolo.weights --train --annotation dataset/kitti/test_annotations --dataset dataset/kitti/test_images --gpu 0.5 --batch 64
`
This is the some part of the output
```
GPU mode with 0.5 usage
cfg/yolo_kitti.cfg loss hyper-parameters:
	H       = 11
	W       = 38
	box     = 5
	classes = 2
	scales  = [1.0, 5.0, 1.0, 1.0]
Building cfg/yolo_kitti.cfg loss
Building cfg/yolo_kitti.cfg train op

```

```
Statistics:
Dataset size: 1496
Dataset of 1496 instance(s)
Training statistics: 
	Learning rate : 1e-05
	Batch size    : 64
	Epoch number  : 1000
	Backup every  : 2000

```

```
2017-06-30 20:01:25.688798: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ******************_____******************************************************************xxxxxxxxxxx
2017-06-30 20:01:25.688840: W tensorflow/core/framework/op_kernel.cc:1152] Resource exhausted: OOM when allocating tensor with shape[64,3,377,1244]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,3,377,1244]
	 [[Node: 0-convolutional_2 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Pad, 0-convolutional/kernel/read)]]
	 [[Node: mul_31/_117 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1293_mul_31", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/mnt/hdd3t/Data/hci2/borinyun/darkflow/darkflow/cli.py", line 29, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "/mnt/hdd3t/Data/hci2/borinyun/darkflow/darkflow/net/flow.py", line 51, in train
    fetched = self.sess.run(fetches, feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,3,377,1244]
	 [[Node: 0-convolutional_2 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Pad, 0-convolutional/kernel/read)]]
	 [[Node: mul_31/_117 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1293_mul_31", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op '0-convolutional_2', defined at:
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/mnt/hdd3t/Data/hci2/borinyun/darkflow/darkflow/cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/mnt/hdd3t/Data/hci2/borinyun/darkflow/darkflow/net/build.py", line 75, in __init__
    self.build_forward()
  File "/mnt/hdd3t/Data/hci2/borinyun/darkflow/darkflow/net/build.py", line 115, in build_forward
    state = op_create(*args)
  File "/mnt/hdd3t/Data/hci2/borinyun/darkflow/darkflow/net/ops/__init__.py", line 27, in op_create
    return op_types[layer_type](*args)
  File "/mnt/hdd3t/Data/hci2/borinyun/darkflow/darkflow/net/ops/baseop.py", line 42, in __init__
    self.forward()
  File "/mnt/hdd3t/Data/hci2/borinyun/darkflow/darkflow/net/ops/convolution.py", line 71, in forward
    name = self.scope, strides = [1] + [self.lay.stride] * 2 + [1])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 403, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[64,3,377,1244]
	 [[Node: 0-convolutional_2 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Pad, 0-convolutional/kernel/read)]]
	 [[Node: mul_31/_117 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1293_mul_31", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```

**Comment by tungalbert99** [comment]
Try reducing batch size?

**Comment by benn94** [comment]
@tungalbert99 I also tried batch =32 an sub =8 still having resource exhaustion problem.

**Comment by benn94** [comment]
Somehow, now it works fine with batch = 32.

**Comment by Wanderish** [comment]
@benn94  any idea how it started to work?

**Comment by LuvRC** [comment]
@thtrieu, @abagshaw please help. Thanks a lot in advance.
