### ISSUE TITLE
failed to allocate 4.00G (4294967296 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by Maurorddr** [thtrieu/darkflow#861]
Hi
We are trying to run Darkflow with gpu in realtime using the web cam on our computer, but we get the following error:

GPU mode with 1.0 usage
2018-08-01 18:48:39.356720: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-08-01 18:48:39.677801: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1406] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2018-08-01 18:48:39.687271: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1485] Adding visible gpu devices: 0
2018-08-01 18:48:41.443087: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-01 18:48:41.452418: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:972]      0
2018-08-01 18:48:41.455503: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:985] 0:   N
2018-08-01 18:48:41.458898: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4096 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-08-01 18:48:41.480500: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc:903] failed to allocate 4.00G (4294967296 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-01 18:48:41.492037: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc:903] failed to allocate 3.60G (3865470464 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
Finished in 16.888976335525513s

Press [ESC] to quit demo
Press [ESC] to quit demo
2018-08-01 18:48:56.140360: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:352] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED

Are we using the wrong device number?
We tryed the following line:
python flow --model cfg/yolo.cfg --load bin/yolo.weights --demo camera --gpu 1.0

When we use "--gpu 0" instead, it runs fine, but it seems to be running with the cpu and not the gpu.

Any ideas?

**Comment by ashleyjsands** [comment]
I assume that your computer is using a small amount of memory for other programs. Try a --gpu value of 0.9, or 0.8 and see if it works.

**Comment by Maurorddr** [comment]
Hey!

Thanks for the answer, it took me a while to figure it out.
I did just what you say and it worked, which made me really happy.

Darkflow rules.
Thanks again

**Comment by doaa90** [comment]
@ashleyjsands @Maurorddr 

Hello , 

I hope ypu can also help me , 
I have Nvidia Geforce GTX 1060 6GB and I cudaa 9 , cudnn 7 , python3.6 , tensorflow 1.12.
I have a classifier using tensorfow and when it try to training the datset it show errors like you 

faild to allocate ....  &  CUDA_ERROR_OUT_OF_MEMORY.

i see the soulation related to change in the gpu value but i didnt know where should i chaange .

I am new in tenserflow
could you please tell me what should I do ? 

thank you for your time

**Comment by doaa90** [comment]
this the error

2018-12-17 17:14:05.927134: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-12-17 17:14:06.533575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2018-12-17 17:14:06.578793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
[I 17:15:06.982 NotebookApp] Saving file at /Traffic_Sign_Classifier.ipynb
[W 17:15:06.985 NotebookApp] Notebook Traffic_Sign_Classifier.ipynb is not trusted
2018-12-17 17:17:31.502382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-17 17:17:31.521375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-12-17 17:17:31.525337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-12-17 17:17:31.607353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4722 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-12-17 17:17:33.034710: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 4.61G (4952306432 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:33.205312: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 4.15G (4457075712 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:33.375447: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.74G (4011367936 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:33.556794: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.36G (3610231040 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:33.737225: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.03G (3249207808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:33.920522: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.72G (2924286976 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:34.102883: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.45G (2631858176 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:34.281883: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.21G (2368672256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:34.465369: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.99G (2131804928 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:34.646585: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.79G (1918624512 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:34.828017: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.61G (1726761984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:35.011160: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.45G (1554085888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:35.187892: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.30G (1398677248 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:35.371399: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.17G (1258809600 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:35.555102: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.05G (1132928768 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:17:35.737914: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 972.40M (1019635968 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-12-17 17:18:49.474109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-12-17 17:18:49.477404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-17 17:18:49.484169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-12-17 17:18:49.488003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-12-17 17:18:49.490366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4722 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
[I 17:19:07.250 NotebookApp] Saving file at /Traffic_Sign_Classifier.ipynb

**Comment by ashleyjsands** [comment]
@doaa90 have you tried using the gpu flag to decrease the amount of memory that you are using? Also, try running `watch -n 1 nvidia-smi` as you run your code again and look at how much free GPU memory you have. You have something else chewing up too much of your memory.
